services:
  photoview-prepare:
    image: photoview/photoview:2
    container_name: photoview-prepare
    network_mode: "none"
    user: root
    entrypoint: []
    command: /bin/bash -c "sleep 1 && mkdir -p /home/photoview/media-cache /home/photoview/database && chown -R photoview:photoview /home/photoview/media-cache /home/photoview/database"
    cap_add:
      - CHOWN
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "${HOST_PHOTOVIEW_LOCATION}/storage:/home/photoview/media-cache"
      - "${HOST_PHOTOVIEW_LOCATION}/database:/home/photoview/database"

  photoview:
    image: photoview/photoview:2
    container_name: photoview
    restart: unless-stopped
    stop_grace_period: 10s
    depends_on:
      photoview-prepare:
        condition: service_completed_successfully
      mariadb:
        condition: service_healthy
    networks:
      - ui_net
      - api_db_net
    ports:
      - "127.0.0.1:8000:80"
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    environment:
      PHOTOVIEW_LISTEN_IP: "0.0.0.0"
      PHOTOVIEW_DATABASE_DRIVER: ${PHOTOVIEW_DATABASE_DRIVER}
      PHOTOVIEW_MYSQL_URL: "${MARIADB_USER}:${MARIADB_PASSWORD}@tcp(photoview-mariadb)/${MARIADB_DATABASE}"
      PHOTOVIEW_UI_ENDPOINTS: ${PHOTOVIEW_UI_ENDPOINTS}
      PHOTOVIEW_PROVIDER_AUTH_ENABLED: ${PHOTOVIEW_PROVIDER_AUTH_ENABLED}
      PHOTOVIEW_PROVIDER_AUTO_PROVISION: ${PHOTOVIEW_PROVIDER_AUTO_PROVISION}
      PHOTOVIEW_PROVIDER_HEALTH_ID_BASE_URL: ${PHOTOVIEW_PROVIDER_HEALTH_ID_BASE_URL}
      PHOTOVIEW_PROVIDER_HEALTH_ID_CLIENT_ID: ${PHOTOVIEW_PROVIDER_HEALTH_ID_CLIENT_ID}
      PHOTOVIEW_PROVIDER_HEALTH_ID_CLIENT_SECRET: ${PHOTOVIEW_PROVIDER_HEALTH_ID_CLIENT_SECRET}
      PHOTOVIEW_PROVIDER_HEALTH_ID_REDIRECT_URI: ${PHOTOVIEW_PROVIDER_HEALTH_ID_REDIRECT_URI}
      PHOTOVIEW_PROVIDER_HEALTH_ID_SCOPE: ${PHOTOVIEW_PROVIDER_HEALTH_ID_SCOPE}
      PHOTOVIEW_PROVIDER_BASE_URL: ${PHOTOVIEW_PROVIDER_BASE_URL}
      PHOTOVIEW_PROVIDER_CLIENT_ID: ${PHOTOVIEW_PROVIDER_CLIENT_ID}
      PHOTOVIEW_PROVIDER_SECRET_KEY: ${PHOTOVIEW_PROVIDER_SECRET_KEY}
      PHOTOVIEW_INITIAL_ROOT_PATH: ${PHOTOVIEW_INITIAL_ROOT_PATH}
      MAPBOX_TOKEN: ${MAPBOX_TOKEN}
      PHOTOVIEW_VIDEO_HARDWARE_ACCELERATION: ${PHOTOVIEW_VIDEO_HARDWARE_ACCELERATION}
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "${HOST_PHOTOVIEW_LOCATION}/storage:/home/photoview/media-cache"
      - "${HOST_PHOTOVIEW_MEDIA_ROOT}:/photos"

  mariadb:
    image: mariadb:lts
    container_name: photoview-mariadb
    restart: unless-stopped
    stop_grace_period: 5s
    command: mariadbd --innodb-buffer-pool-size=512M --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=120
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    networks:
      - api_db_net
    environment:
      MARIADB_AUTO_UPGRADE: "1"
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "${HOST_PHOTOVIEW_LOCATION}/database/mariadb:/var/lib/mysql"
    healthcheck:
      test: healthcheck.sh --connect --innodb_initialized
      interval: 1m
      timeout: 5s
      retries: 5
      start_period: 3m

networks:
  ui_net:
    driver: bridge

  api_db_net:
    internal: true
